FROM node:16.14.2-alpine
LABEL author="ivan pedro arteaga"

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app/
RUN npm install -g npm@8.6.0
RUN npm install

# Bundle app source
COPY . /usr/src/app

EXPOSE 3000
# CMD ["npm", "start" ]
CMD ["node", "index.js" ]